feat: support default theme styles
stoplightio/storybook-config pull request #2
Opened 2019-01-07 18:09 UTC by P0lip

It was requested a couple of days ago by Will and IMHO it makes sense to have such a feature included given it was easy to implement.
In general, most of the satellite projects such as Formtron, Slate or Tree-List will inherit some styling.
At the moment, it's quite difficult to mimic such styles. The only way to do that is to wrap each story (global decorators cannot be used until Storybook v5 is released) with a decorator containing the styled component.
This may be annoying.

To make further styling easier, `defaultThemeStyles` has been introduced to the theme.js Storybook config.

You can put any CSS rule and it will be automatically injected into the theme wrapper as long as you have the checkbox ticket, i.e.

```ts
export const defaultThemeStyles = {
  dark: {
    backgroundColor: '#111',
    color: '#fff',
  },
  light: {
    backgroundColor: '#fff',
    color: '#111',
  }
};
```
![storybook2](https://user-images.githubusercontent.com/9273484/50784882-4522dc00-12af-11e9-80e8-0fcc0d366688.gif)

If styles are not present, nothing happens. The change is backward compatible meaning existing projects won't break if they don't export `defaultThemeStyles`.

2019-01-07 21:09 UTC, wmhilton commented
How exactly do you use it? (or how do I test it / try it out?)

2019-01-08 12:47 UTC, P0lip commented
@wmhilton 
This is the way I tested it (no yalc required):

1. check out this branch and build the project
2. copy the build directory
3. go to any project that already uses storybook-config
4. and paste the build directory to `node_modules/@stoplight/storybook-config`
5. edit (or create) theme.js located under `.storybook` in the root of the project
6. add the following styles (can be though)
```
export const defaultThemeStyles = {
  dark: {
    backgroundColor: '#111',
    color: '#fff',
  },
  light: {
    backgroundColor: '#fff',
    color: '#111',
  }
};
```
7. run Storybook as usually
8. the checkbox should be in place

2019-01-08 16:50 UTC, wmhilton commented
Turns out that all the packages I'm familiar with (`formtron`, `@stoplight/slate-editor`, `@stoplight/ui-kit`) haven't been upgraded to `@stoplight/scripts@4.x` and so none of them use `@stoplight/storybook-config` AFAICT. I tried to upgrade some of them but got lost/confused.

Oh, looks like `@stoplight/tree-list` uses scripts 4.x. hang on...

2019-01-08 17:02 UTC, P0lip commented
@wmhilton Formtron has storybook-config included.

2019-01-08 17:03 UTC, wmhilton commented
I'm a little confused. The example you give uses CSS properties:

```js
export const defaultThemeStyles = {
  dark: {
    backgroundColor: '#111',
    color: '#fff',
  },
  light: {
    backgroundColor: '#fff',
    color: '#111',
  }
};
```

I was expecting it to be Theme properties, like:
```js
export const defaultThemeStyles = {
  dark: {
    canvas: {
      bg: '#111',
      fg: '#fff',
  },
  light: {
    canvas: {
      bg: '#fff',
      fg: '#111',
  }
};
```

I'm coming down with a cold though, maybe I just need a break.

2019-01-08 17:33 UTC, P0lip commented
I understand the theme properties could be better, but the problem is that they are not too explicit, so I wouldn't really know how to properly attach them.
I mean, both canvas.bg and canvas.fg can be used for everything, not just for background and color.
Also, what if canvas is empty or named differently?

Maybe the naming is wrong then?

2019-01-08 21:29 UTC, billiegoose commented
> @wmhilton Formtron has storybook-config included.

You're absolutely right, I'm just out of it today.

2019-01-08 22:04 UTC, wmhilton commented
OK, I get it!
This:
![image](https://user-images.githubusercontent.com/587740/50861160-e10f1f00-1365-11e9-9dcd-d827a2238cb8.png)

is arguably much better than this:
![image](https://user-images.githubusercontent.com/587740/50861213-fe43ed80-1365-11e9-9569-187e0293f77b.png)

But the fact that it's done by injecting plain CSS styles is disconcerting. Because now we have two things tied to each `base` theme: the theme rules _and_ some random top-level CSS props.

Lemme ponder this a bit. See if there's an elegant solution trying to work its way out.

2019-01-08 23:54 UTC, wmhilton commented
@P0lip this repo (`storybook-config`) doesn't have a dependency on `ui-kit` does it? So we can't directly use components like `Box`, only what's exported by the project like `ThemeProvider`?

2019-01-09 00:05 UTC, P0lip commented
You are right, it doesn't depend on UI-Kit, therefore you can only use what's exported.

2019-01-09 16:54 UTC, billiegoose requested changes
Alright. Here's my thoughts.

I don't like `themeDefaultStyles` because it is CSS specific to Storybook _and_ specific to each project. That makes it extremely likely that the colors will get "out-of-sync" with the actual themes.

Imagine if we changed the default `canvas.bg` color in Studio. Now, if we want to see the "correct" dark theme background color in Storybook, we would have to update the `themeDefaultStyles` in `formtron`, `ui-kit`, `slate-editor`, `tree-list`, `json-schema-viewer`....

I think I have an alternative that avoids that problem though! Here's my proposal: What if we define the values for `canvas: { fg, bg }` in a new package, like `@stoplight/canvas-theme`. And then here in `storybook-config` and in `studio` we can have a dependency on that package and set the `backgroundColor` and `color` using that?

2019-03-18 19:13 UTC, marbemac commented
Is this still relevant?

2019-03-19 12:06 UTC, P0lip commented
@marbemac 
Yes, it's still relevant. We didn't push forward with the PR, as we had more important issues/tasks to tackle, but I believe we still need to do something about it to improve DX.
At the moment, most of the projects have some wrapper every story that adds background and color, in particular for the dark theme.
The following PR tries to address that issue so that the mentioned wrapper is no longer needed.

2019-04-26 14:49 UTC, closed without merging